<template>
    <div>
        <form class="form-inline"  v-on:submit.prevent>
            <div class="form-group">
                <el-date-picker
                v-model="dateTEST"
                type="date"
                format="yyyy-MM-dd"
                placeholder="Date"
                ref="setDate">
                </el-date-picker>
            </div>
            <div class="form-group">
                
                <select 
                    class="form-control" 
                    v-if="!addEmployeeName"
                    @change="employeeSelectHandler"
                    v-model="newEmployeeNameSet"
                    >
                    <option disabled value="default">Select employee</option>
                    <!--<option v-for="wage in employeeNames" v-bind:value="wage.name">{{wage.name}}</option>-->
                    <option v-for="person in people" v-bind:value="{name: person.name, id: person.id} ">
                        {{person.name}}
                    </option>
                    <option value="addNew">Add new employee</option>
                </select>
                
            </div>
            
            <div class="form-group">
                <input class="form-control" v-model="wageAmount" type="number" step="0.01" placeholder="0.00">
            </div>
            
            <button @click="addWage" class="btn btn-default">Add</button>
        </form>


        
        <el-dialog title="Add new employee" v-model="addEmployeeModal" size="small">
            <span>Enter full name</span>
            <app-add-company-person :user="user"></app-add-company-person>
            <span slot="footer" class="dialog-footer">
                <el-button @click="addEmployeeModal = false">Cancel</el-button>      
            </span>
        </el-dialog>
        
    </div>
</template>

<script>
    import * as firebase from 'firebase/app';
    import {config} from '../firebase/config.js'
    import getWages from '../mixins'
    import filtersOff from '../mixins'
    import {mapActions} from 'vuex'
    import addCompanyPerson from '../people/AddCompanyPerson.vue'
    import companyPersonSelect from '../people/CompanyPersonSelect.vue'
    import getTradingYear from '../mixins'
    
    export default {
        data() {
            return {
                wageAmount: 0.00,
                addEmployeeName: false,
                newEmployeeName: '',
                newEmployeeNameSet: 'default',
                nameID: '',
                dateTEST: '',
                addEmployeeModal: false
                
            }
        },
        
        mixins: [getWages, filtersOff],
        components: {
            appAddCompanyPerson: addCompanyPerson
        },
        computed: {
            loginState() {
                return this.$store.getters.login
            },
            people() {
                return this.$store.getters.people
            },
            addPersonVisible(){
                return this.$store.getters.addPersonVisible
            },
            employeeNames() {
                return this.$store.getters.employeeNames
            },
                   
        },
  
        methods:{
            ...mapActions([
                'removeFilterWages',
                'setPersonModal',
            ]),
            
            employeeSelectHandler(e){
                if(e.target.value === 'addNew') { 
                    
                    this.addEmployeeModal = true
                    this.setPersonModal(true);
                    //this.$refs.newEmployeeInput.focus();
                }
            },
            addWage(){
                //we set which trading year the invoice goes in
                this.getTradingYear(this.$refs.setDate.displayValue)


                const db = firebase.database().ref('users/'+ this.user.uid).child('/wages/');
                const ref = db.push().key;
                //hide the set new type of expense input field
               
                //get data ready to set in our firebase db ref
                //store the key generated by firebase in this object so we can easily access the key for say delete or update methods 
                //see delete in Expenses2.vue
                var timestamp = Date.now();
                
                var newData = {
                    name: this.newEmployeeNameSet.name,
                    nameID: this.newEmployeeNameSet.id,
                    wage: this.wageAmount,
                    id: ref,
                    timestamp: timestamp,
                    date: this.$refs.setDate.displayValue,
                    tradingYear: this.$store.getters.tradingYear
                };
                
                db.child(ref).set(newData);
               
                this.getWages();
                this.removeFilterWages();
                this.filtersOff();

            }
           
        },
        watch: {
            //bit of a hack here to get the modal to close via state and default close methods with element(esc key, close icon, modal click etc...)
            addEmployeeModal: function (val) {
               if (val === false){
                   this.setPersonModal(false)
                   this.newEmployeeNameSet = 'default'
               }
            },
            addPersonVisible:function(val){
                if (val === false){
                    this.addEmployeeModal = false
               }
            }
            
        },
        created() {
            this.getWages();
        }
    }
</script>
<style>
    .newEmployeeInput {
        opacity:0;
        position: absolute;
        left:-9999px;
    }
    .newEmployeeInput.visible {
        position: relative;
        left: 0;
        opacity:1;
    }
</style>
