<template>
    <div>
        <form class="form-inline"  v-on:submit.prevent>
            <div class="form-group">
                <input 
                    placeholder="company name" 
                    class="form-control" 
                    type="text" 
                    v-model="companyName" 
                >
            </div>
            <div class="form-group">
                <el-date-picker
                    v-model="incorporationDate"
                    type="date"
                    format="dd-MM-yyyy"
                    placeholder="Incorporation Date"
                    ref="setDate">
                </el-date-picker>
            </div>
            <div class="form-group">
                VAT
                <input type="radio" id="yesVAT" value="yesVAT" v-model="setVAT">
                <label for="one">Yes</label>
                <br>
                <input type="radio" id="noVAT" value="noVAT" v-model="setVAT">
                <label for="two">No</label>
                £{{expenseAmountVAT}}
            </div>
            
            <button @click="saveCompanyDetails" class="btn btn-default">Save</button>
        </form>
    </div>
</template>

<script>
    import * as firebase from 'firebase';
   
    import {config} from '../firebase/config.js'
    
    import getCompanyDetails from '../mixins'
    
    import {mapActions} from 'vuex'

    
    export default {
        data() {
            return {
                companyName : '',
                incorporationDate: '',
                setVAT: 'noVAT',
                companyDetails: this.company,
                edit: false
            }
        },
       
        mixins: [getCompanyDetails],
        computed: {
            loginState() {
                return this.$store.getters.login
            },
            
            date(){
                var timestamp = new Date();
                
                const date = timestamp.getDate();
                const month = timestamp.getMonth() + 1;
                const year = timestamp.getFullYear();

                return date + '-' + month + '-' + year 
            }  
        },

        
            
        methods:{
            ...mapActions([
                
            ]),
            
            
            saveCompanyDetails(){
                const db = firebase.database().ref('users/'+ this.user.uid).child('company/');
                
                
                //get data ready to set in our firebase db ref
                //store the key generated by firebase in this object so we can easily access the key for say delete or update methods 
                //see delete in Expenses2.vue
                let timestamp = Date.now();
                
                let newData = {
                    company: this.companyName,
                    //incorporationDate: this.incorporationDate,
                    date: this.$refs.setDate.displayValue
                };
                
                db.set(newData);
               
                this.getCompanyDetails();
                this.edit = false
            }
           
        },
        created() {
            //this.getCompanyDetails();
        }
    }
</script>
<style>

</style>
