<template>
    <div>
        <form class="form-inline"  v-on:submit.prevent>
            <div class="form-group">
                <el-date-picker
                v-model="dateTEST"
                type="date"
                format="dd-MM-yyyy"
                placeholder="Date"
                ref="setDate">
                </el-date-picker>
            </div>
            <div class="form-group">
                <input 
                    placeholder="expense type" 
                    class="form-control newExpenseInput" 
                    :class="{ visible: addExpenseType}" 
                    type="text" 
                    v-model="newExpenseType" 
                    ref="newExpenseInput"
                >
                <select 
                    class="form-control" 
                    v-if="!addExpenseType"
                    @change="expenseSelectHandler"
                    v-model="newExpenseTypeSET"
                    >
                    <option disabled value="default">Select type</option>
                    <option v-for="type in expenseTypes" v-bind:value="type.type">{{type.type}}</option>
                    <option value="addNew">Add new type</option>
                </select>
            </div>
            <div class="form-group">
                <input placeholder="name / description" class="form-control " v-model="expenseName" type="text">
            </div>
            <div class="form-group">
                <input class="form-control" v-model="expenseAmount" type="number" step="0.01" placeholder="0.00">
            </div>
            <div class="form-group">
                VAT
                <input type="radio" id="yesVAT" value="yesVAT" v-model="setVAT">
                <label for="one">Yes</label>
                <br>
                <input type="radio" id="noVAT" value="noVAT" v-model="setVAT">
                <label for="two">No</label>
                {{expenseAmountVAT | currency('£')}}
            </div>
            <button @click="addExpense" class="btn btn-default">Add</button>
        </form>            
    </div>
</template>

<script>
    import * as firebase from 'firebase/app';
   
    import {config} from '../firebase/config.js'
    
    import getExpenses from '../mixins'
    import getTradingYear from '../mixins'
    import filtersOff from '../mixins'
    
    import {mapActions} from 'vuex'
    
    
    
    export default {
        data() {
            return {
                expenseName : '',
                expenseAmount: 0.00,
                addExpenseType: false,
                newExpenseType: '',
                newExpenseTypeSET: 'default',
                dateTEST: '',
                setVAT: 'noVAT'
            }
        },
        
        mixins: [getExpenses, filtersOff, getTradingYear],
        computed: {
            loginState() {
                return this.$store.getters.login
            },
            
            expenseTypes() {
                return this.$store.getters.expenses2Types
            },
            setDefaultExpenseType() {
                return this.newExpenseTypeSET;
            },
            
            expenseAmountVAT(){
                if (this.setVAT == 'noVAT') {
                    return this.expenseAmount
                }
                else {
                    return this.expenseAmount*(1+(this.$store.getters.VATRate/100)).toFixed(2);
                }
                
            }

               
        },

        
            
        methods:{
            ...mapActions([
                'setExpenses',
                'setExpenses2',
                'setExpenseTypes',
                'setFilteredExpenses',
                'removeFilterByExpenses'
            ]),
            expenseSelectHandler(e){
                if(e.target.value === 'addNew') { 
                    this.addExpenseType = true;
                    this.$refs.newExpenseInput.focus();
                }
            },
            
            addExpense(){
                //we set which trading year the invoice goes in
                this.getTradingYear(this.$refs.setDate.displayValue)

                const db = firebase.database().ref('users/'+ this.user.uid).child('/expenses2/');
                const ref = db.push().key;
                //hide the set new type of expense input field
                let type = '';
                if(this.addExpenseType){
                    type = this.newExpenseType
                }
                else {
                    type = this.newExpenseTypeSET              
                }
                
                //get data ready to set in our firebase db ref
                //store the key generated by firebase in this object so we can easily access the key for say delete or update methods 
                //see delete in Expenses2.vue
                var timestamp = Date.now();
                
                var newData = {
                    type: type,
                    name: this.expenseName,
                    amount: this.expenseAmount,
                    amountVAT: this.expenseAmountVAT,
                    id: ref,
                    timestamp: timestamp,
                    date: this.$refs.setDate.displayValue,
                    tradingYear: this.$store.getters.tradingYear
                };
                
                db.child(ref).set(newData);
               
                this.getExpenses();
                this.removeFilterByExpenses();
                this.filtersOff();

                //if we're adding a new expense type
                if(this.addExpenseType){
                    //set the dropdown to the one we just added
                    this.newExpenseTypeSET = this.newExpenseType
                    //hide the manual input for new expense
                    this.addExpenseType = false
                    
                }
                else {
                    this.newExpenseType = '';
                }

            }
           
        },
        created() {
            this.getExpenses();
        }
    }
</script>
<style>

    .newExpenseInput {
        opacity:0;
        position: absolute;
        left:-9999px;
    }
    .newExpenseInput.visible {
        position: relative;
        left: 0;
        opacity:1;
    }
</style>
