<template>
    <div>
        <form class="form-inline"  v-on:submit.prevent>
            <div class="form-group">
                <el-date-picker
                    v-model="dateTEST"
                    type="date"
                    format="dd-MM-yyyy"
                    placeholder="Date"
                    ref="setDate">
                </el-date-picker>
            </div>
            <div class="form-group">
                
                <select 
                    class="form-control" 
                    @change="shareholderSelectHandler"
                    v-model="newShareholderNameSet"
                    >
                    <option disabled value="default">Select shareholder</option>
        
                    <option v-for="person in people" v-bind:value="{name: person.name, id: person.id} ">
                        {{person.name}}
                    </option>
                    <option value="addNew">Add new shareholder</option>
                </select>
            </div>
            
            <div class="form-group">
                <input class="form-control" v-model="dividendAmount" type="number" step="0.01" placeholder="0.00">
            </div>
            
            <button @click="addShareholder" class="btn btn-default">Add</button>
        </form> 
        
         <el-dialog title="Add a new shareholder" v-model="addShareholderModal" size="tiny">
            <span>Enter full name</span>
            <app-add-company-person :user="user"></app-add-company-person>
            <span slot="footer" class="dialog-footer">
                <el-button @click="addShareholderModal = false">Cancel</el-button>
            </span>
        </el-dialog>           
    </div>
</template>

<script>
    import * as firebase from 'firebase';
   
    import {config} from '../firebase/config.js'
    
    import getDividends from '../mixins'
    import getTradingYear from '../mixins'
    import filtersOff from '../mixins'
    
    import {mapActions} from 'vuex'
    
    import addCompanyPerson from '../people/AddCompanyPerson.vue'
    
    
    
    export default {
        data() {
            return {
                dividendAmount: 0.00,
                newShareholderNameSet: 'default',
                dateTEST: '',
                addShareholderModal: false
            }
        },
        
        mixins: [getDividends, filtersOff],
        components: {
            appAddCompanyPerson: addCompanyPerson
        },
        computed: {
            loginState() {
                return this.$store.getters.login
            },
            
            people() {
                return this.$store.getters.people
            },
            addPersonVisible(){
                return this.$store.getters.addPersonVisible
            },    
        },

        
            
        methods:{
            ...mapActions([
                'removeFilterDividends',
                'setPersonModal'
            ]),
            shareholderSelectHandler(e){
                if(e.target.value === 'addNew') { 
                    this.addShareholderModal = true
                    this.setPersonModal(true);
                }
            },
            cancelHandler(){
                this.setPersonModal(false)
                this.newShareholderNameSet = 'default'
            },
            addShareholder(){
                //we set which trading year the invoice goes in
                this.getTradingYear(this.$refs.setDate.displayValue)

                const db = firebase.database().ref('users/'+ this.user.uid).child('/dividends/');
                const id = db.push().key;
                
                //get data ready to set in our firebase db ref
                //store the key generated by firebase in this object so we can easily access the key for say delete or update methods 
                //see delete in Expenses2.vue
                var timestamp = Date.now();
                
                var newData = {
                    name: this.newShareholderNameSet.name,
                    nameID: this.newShareholderNameSet.id,
                    dividend: this.dividendAmount,
                    id,
                    timestamp,
                    date: this.$refs.setDate.displayValue,
                    tradingYear: this.$store.getters.tradingYear
                };
                
                db.child(id).set(newData);
               
                this.getDividends();
                this.removeFilterDividends();
                this.filtersOff();

                

            }
           
        },
        watch: {
            //bit of a hack here to get the modal to close via state and default close methods with element(esc key, close icon, modal click etc...)
            addShareholderModal: function (val) {
               if (val === false){
                   this.setPersonModal(false)
                   this.newShareholderNameSet = 'default'
               }
            },
            addPersonVisible:function(val){
                if (val === false){
                    this.addShareholderModal = false
               }
            }
            
        },
        created() {
            this.getDividends();
        }
    }
</script>

