<template>
    <div>
        <form class="form-inline"  v-on:submit.prevent>
            <div class="form-group">
                <el-date-picker
                v-model="invDate"
                type="date"
                format="dd-MM-yyyy"
                placeholder="Date"
                ref="setDate">
                </el-date-picker>
            </div>
            <div class="form-group">
                <input 
                    placeholder="Company Name" 
                    class="form-control newCompanyNameInput" 
                    :class="{ visible: addCompanyName}" 
                    type="text" 
                    v-model="newCompanyName" 
                    ref="newCompanyNameInput"
                >
                <select 
                    class="form-control" 
                    v-if="!addCompanyName"
                    @change="companyNameSelectHandler"
                    v-model="newCompanyNameSet"
                    >
                    <option disabled value="default">Select company</option>
                    <option v-for="company in companies" v-bind:value="company">{{company}}</option>
                    <option value="addNew">Add new company</option>
                </select>
            </div>
            <div class="form-group">
                <input class="form-control" v-model="invoiceDescription" type="text" placeholder="Description">
            </div>
            <div class="form-group">
                <input class="form-control" v-model="invoiceAmount" type="number" step="0.01" placeholder="0.00">
            </div>
            <button @click="addInvoice" class="btn btn-default">Add</button>
            
            <div class="form-group">
                INC VAT £{{invoiceAmountVAT}}
            </div>
            
        </form>            
    </div>
</template>

<script>
    import * as firebase from 'firebase/app';
   
    import {config} from '../firebase/config.js'
    
    import getInvoices from '../mixins'
    import getTradingYear from '../mixins'
    import filtersOff from '../mixins'
    
    import {mapActions} from 'vuex'

    import {addDecimals} from '../../lib/decimal-operations'
    
    export default {
        data() {
            return {
                invoiceDescription: '',
                invoiceAmount: 0.00,
                addCompanyName: false,
                newCompanyName: '',
                newCompanyNameSet: 'default',
                invDate: ''
            }
        },
     
        mixins: [getInvoices, filtersOff],
        computed: {
            loginState() {
                return this.$store.getters.login
            },
            invNum(){
                return this.$store.getters.invoicesLength +1
            },
            invoicesCompanies() {
                return this.$store.getters.invoicesCompanies
            },
            invoiceAmountVAT(){
                let n = this.invoiceAmount*(1+(this.$store.getters.VATRate/100));
                return Number(n).toFixed(2);
            },
            companies() {
                return this.$store.getters.companies
            },

               
        },

        
        methods:{
            ...mapActions([
                'removeFilterInvoices'
            ]),
            companyNameSelectHandler(e){
                if(e.target.value === 'addNew') { 
                    this.addCompanyName = true;
                    this.$refs.newCompanyNameInput.focus();
                }
            },
            
            addInvoice(){
                //we set which trading year the invoice goes in
                this.getTradingYear(this.$refs.setDate.displayValue)

                const db = firebase.database().ref('users/'+ this.user.uid).child('/invoices/');
                const id = db.push().key;
                //hide the set new type of expense input field
                let company = '';
                if(this.addCompanyName){
                    company = this.newCompanyName
                }
                else {
                    company = this.newCompanyNameSet              
                }
                
                //get data ready to set in our firebase db ref
                //store the key generated by firebase in this object so we can easily access the key for say delete or update methods 
                //see delete in Expenses2.vue
                var timestamp = Date.now();
                
                var newData = {
                    id,
                    timestamp,
                    date: this.$refs.setDate.displayValue,
                    invNum: this.invNum,
                    company,
                    invoiceDescription: this.invoiceDescription,
                    amount: this.invoiceAmount,
                    amountVAT: this.invoiceAmountVAT,
                    tradingYear: this.$store.getters.tradingYear
                };
                
                db.child(id).set(newData);
               
                this.getInvoices();
                this.removeFilterInvoices();
                this.filtersOff();

                //if we're adding a new inv company
                if(this.addCompanyName){
                    //set the dropdown to the one we just added
                    this.newCompanyNameSet = this.newCompanyName
                    //hide the manual input for company
                    this.addCompanyName = false
                    
                }
                else {
                    this.newCompanyName = '';
                }

            }
           
        },
        created() {
            this.getInvoices();
        }
    }
</script>
<style>
    .newCompanyNameInput {
        opacity:0;
        position: absolute;
        left:-9999px;
    }
    .newCompanyNameInput.visible {
        position: relative;
        left: 0;
        opacity:1;
    }
</style>
